### ISSUE TITLE
unsquashfs not present in cedar-14

### ISSUE THREAD

**Issue by fdr** [ddollar/heroku-docker#2]
I don't see how this particular line can work (and it busts up on one of my apps that uses `squashfs`)

https://github.com/ddollar/heroku-docker/blob/8ec4611829119f677f41769b6f3b846f1ab66ac8/init.rb#L182

That's because the cedar image doesn't have `unsquashfs` present, AFAICS.

**Comment by ddollar** [comment]
Looks like I'm making some unwarranted assumptions about cedar14. I'll have to look into building an image based on heroku/cedar:14 that has unsquashfs inside.
